
add_newline = false


[character] 
success_symbol = "[â•šâ•{](#00416a)"
error_symbol = "[â•š](#00416a)[ğ—¡ ğ—¢ ](#660000)[â•{](#00416a)"


[package]

disabled = true


[username]

format = "[â•”â•â•â•â•{](#00416a)[USER:](#996515)[$user](#996515)[}â•{â‹‡ }](#00416a)"
disabled = false
show_always = true


[directory]

truncation_length = 10
truncation_symbol = ""
style = "fg:purple"


[git_branch]

always_show_remote = true
format = "on [$symbol$branch](#FF4B00) "
symbol = "î‚  "
disabled = false


[git_status]
conflicted = '[ğŸ³\($count\)](red)'
ahead = '[ğŸ\($count\)](white)'
behind = '[ğŸ˜°\($count\)](white)'
diverged = '[ğŸ˜µ\($count\)](white)'
untracked = '[â”\($count\)](white)'
stashed = '[ğŸ“¦\($count\)](white)'
modified = '[ğŸ“\($count\)](white)'
staged = '[âœ…\($count\)](green)'
renamed = '[ğŸ‘…\($count\)](white)'
deleted = '[ğŸ—‘\($count\)](white)'

