add_newline = false


[character] 
success_symbol = "[â•šâ•{](#0080FF)"
error_symbol = "[â•š](#0080FF)[ğ—¡ ğ—¢ ](#660000)[â•{](#0080FF)"


[package]

disabled = true


[username]

format = "[â•”â•â•â•â•{](#0080FF)[USER:](#FFFF00)[$user](#FFFF00)[}â•{](#0080FF)"
disabled = false
show_always = true


[directory]

truncation_length = 10
truncation_symbol = ""
style = "(#6600CC)"


[git_branch]

always_show_remote = true
format = "on [$symbol$branch](#FF4B00) "
symbol = "î‚  "
disabled = false


[git_status]
conflicted = '[ğŸ³\($count\)](red)'
ahead = '[ğŸ\($count\)](white)'
behind = '[ğŸ˜°\($count\)](white)'
diverged = '[ğŸ˜µ\($count\)](white)'
untracked = '[â”\($count\)](white)'
stashed = '[ğŸ“¦\($count\)](white)'
modified = '[ğŸ“\($count\)](white)'
staged = '[âœ…\($count\)](green)'
renamed = '[ğŸ‘…\($count\)](white)'
deleted = '[ğŸ—‘\($count\)](white)'
